# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

jobs:
  build:
    docker:
      - image: maven:3.8.1-openjdk-17-slim
    environment:
      MAVEN_CLI_OPTS: "--batch-mode"

    steps:
      - checkout
      - run:
        name: Build Project with Dependencies
        command: |
          npm install express@9.5.1
          mvn clean package -Pproduction -e

      - store_artifacts:
          path: target
          destination: target

  test:
    docker:
      - image: maven:3.8.1-openjdk-17-slim
    steps:
      - checkout
      - run:
          name: Save test results
          command: |
            mvn test -e
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results/junit/
          destination: ~/test-results/junit/

workflows:
  Test-and-Build:
    jobs:
      - test
      - build:
          requires:
            - test
