version: 2.1

jobs:
  build:
    docker:
      - image: maven:3.8.1-openjdk-17-slim
    environment:
      MAVEN_CLI_OPTS: "--batch-mode"

    steps:
      - checkout
      - run: mvn $MAVEN_CLI_OPTS clean -DskipTests package -Pproduction -e

      - store_artifacts:
          path: target
          destination: target

  test:
    docker:
      - image: circleci/openjdk:17-buster
        environment:
          CHROME_BIN: /usr/bin/google-chrome-stable
          DISPLAY: ":99"

    steps:
      - checkout
      - run: sudo apt-get update && sudo apt-get install -y wget curl unzip xvfb libxi6 libgconf-2-4
      - run: |
          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
          sudo apt-get update && sudo apt-get install -y google-chrome-stable

      - run: |
          CHROME_DRIVER_VERSION=$(curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE)
          wget -q -O /tmp/chromedriver.zip http://chromedriver.storage.googleapis.com/$CHROME_DRIVER_VERSION/chromedriver_linux64.zip
          sudo unzip -q /tmp/chromedriver.zip -d /usr/local/bin
          sudo chmod +x /usr/local/bin/chromedriver

      - run: |
          Xvfb :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
          export DISPLAY=:99

      - run: mvn $MAVEN_CLI_OPTS test

      - store_test_results:
          path: target/surefire-reports
          destination: test-results

workflows:
  Test-and-Build:
    jobs:
      - build
      - test:
          requires:
            - build
