# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# GCP Orb for GCP deployment
orbs:
  gcp-cli: circleci/gcp-cli@3.1.0
  cloud-run: circleci/gcp-cloud-run@1.0.2
  gcp-gcr: circleci/gcp-gcr@0.15.1

executors:
  gcloud-executor:
    docker:
      - image: google/cloud-sdk

  machine-executor:
    machine: true

jobs:

  build:
    docker:
      - image: maven:3.8.1-openjdk-17-slim
    environment:
      MAVEN_CLI_OPTS: "--batch-mode"

    steps:
      - checkout
      - run: mvn $MAVEN_CLI_OPTS clean package -Pproduction -e

      - store_artifacts:
          path: target
          destination: target

  test:
    docker:
      - image: maven:3.8.1-openjdk-17-slim
    steps:
      - checkout
      - run:
          name: Save test results
          command: |
            mvn test -e
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results/junit/
          destination: ~/test-results/junit/

  build_push_image_gcr:
    description: Build docker image and push to gcr registry
    executor: gcp-gcr/default
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - gcp-gcr/gcr-auth
      - gcp-gcr/build-image:
          dockerfile: Dockerfile
          google-project-id: GOOGLE_PROJECT_ID
          image: sp-69-test
          registry-url: "eu.gcr.io"
          tag: "latest"
      - gcp-gcr/push-image:
          google-project-id: GOOGLE_PROJECT_ID
          image: sp-69-test
          registry-url: "eu.gcr.io"
          tag: "latest"

  gcp_cloud_run_deploy:
    description: Deploy using cloud run
    executor: machine-executor
    steps:
      - cloud-run/init
      - cloud-run/deploy:
          platform: 'managed'
          image: 'eu.gc.io/$GOOGLE_PROJECT_ID/sp-69-test'
          service-name: 'error-annihilator'
          region: 'europe-west1'
          unauthenticated: true

workflows:
  push-image-and-deploy-to-gcr:
    jobs:
      - build_push_image_gcr
      - gcp_cloud_run_deploy:
          requires:
            - build_push_image_gcr

  Test-and-Build:
    jobs:
      - build
      - test:
          requires:
            - build