# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

jobs:
  build:
    docker:
      - image: maven:3.8.1-openjdk-17-slim
    environment:
      MAVEN_CLI_OPTS: "--batch-mode"
      VAADIN_OFFLINE_KEY: '245f05ad-ec2f-4865-be9c-bc748ade3d8a'

    steps:
      - checkout
      - run:
          command: mvn $MAVEN_CLI_OPTS clean package -Pproduction -Dvaadin.productionMode -Dvaadin.offline -Dvaadin.offline.key=$VAADIN_OFFLINE_KEY -e
      - store_artifacts:
          path: target
          destination: target

  test:
    docker:
      - image: maven:3.8.1-openjdk-17-slim
    steps:
      - checkout
      - run:
          name: Save test results
          command: |
            mvn test -e
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results/junit/
          destination: ~/test-results/junit/

workflows:
  Test-and-Build:
    jobs:
      - test
      - build:
          requires:
            - test
