# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# GCP Orb for GCP deployment
orbs:
  gcp-cli: circleci/gcp-cli@3.1.0
#  gcp-cloud-run: circleci/gcp-cloud-run@1.0.2
#  gcp-gcr: circleci/gcp-gcr@0.15.1

executors:
  gcloud-executor:
    docker:
      - image: google/cloud-sdk

  machine-executor:
    machine: true

jobs:
  use-gcp:
    executor: gcp-cli/default
    steps:
      - gcp-cli/setup:
          version: 404.0.0

      - run:
          name: authenticate with GCP-SA-Key
          command: |
            echo $GCLOUD_SERVICE_KEY | base64 --decode >> /tmp/circleci/gcloud-service-key.json
            gcloud_auth_activate_service-account --key-file=/tmp/circleci/gcloud-service-key.json

  build:
    docker:
      - image: maven:3.8.1-openjdk-17-slim
    environment:
      MAVEN_CLI_OPTS: "--batch-mode"

    steps:
      - checkout
      - run: mvn $MAVEN_CLI_OPTS clean package -Pproduction -e

      - store_artifacts:
          path: target
          destination: target

  test:
    docker:
      - image: maven:3.8.1-openjdk-17-slim
    steps:
      - checkout
      - run:
          name: Save test results
          command: |
            mvn test -e
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results/junit/
          destination: ~/test-results/junit/

workflows:
  install-and-configure-cli:
    jobs:
      - use-gcp:
          context: ErrorAnnihilator

  Test-and-Build:
    jobs:
      - test
      - build:
          requires:
            - test